version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
#    volumes:
#      - type: bind
#        source: ./docker/mongodb
#        target: /docker-entrypoint.init.d/
    volumes:
      - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: the-user
      MONGO_INITDB_ROOT_PASSWORD: the-password
      MONGO_INITDB_DATABASE: pokedex
    ports:
      - "27017:27017"
