---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/pokemon":
    get:
      tags:
        - search-pokemon-resource
      operationId: search
      parameters:
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/PokemonDTO"
components:
  schemas:
    PokemonDTO:
      type: object
      properties:
        number:
          type: integer
          format: int32
        name:
          type: string
        type:
          type: string
