---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/trainer/{trainerId}/pokemon/favorites":
    get:
      tags:
        - get-favorites-pokemon-resources
      operationId: get
      parameters:
        - name: trainerId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/PokemonDTO"
        '404':
          description: Not Found
    put:
      tags:
        - put-favorites-pokemon-resources
      operationId: set
      parameters:
        - name: trainerId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SetTrainerFavoritesDTO"
        required: true
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  "/pokemon":
    get:
      tags:
        - search-pokemon-resource
      operationId: search
      parameters:
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/PokemonDTO"
  "/pokemon/{pokemonNumber}":
    get:
      tags:
        - get-pokemon-resource
      operationId: get_1
      parameters:
        - name: pokemonNumber
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PokemonDTO"
        '404':
          description: Not Found
components:
  schemas:
    SetTrainerFavoritesDTO:
      type: object
      properties:
        favorites:
          uniqueItems: true
          type: array
          items:
            type: integer
            format: int32
    PokemonDTO:
      type: object
      properties:
        number:
          type: integer
          format: int32
        name:
          type: string
        type:
          type: string
